// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TDH.Basketball.Game.EF.Core;

namespace TDH.Basketball.Game.Home.Migrations
{
    [DbContext(typeof(TDHDBContext))]
    [Migration("20200302054922_add payment code")]
    partial class addpaymentcode
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.Attendee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("EventId")
                        .HasColumnType("int");

                    b.Property<decimal>("FeeShared")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("IsPermanent")
                        .HasColumnType("bit");

                    b.Property<DateTime>("PaidDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentCode")
                        .HasColumnType("varchar(10)");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<int>("ReplacedPlayerId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("EventId");

                    b.HasIndex("PlayerId");

                    b.HasIndex("ReplacedPlayerId");

                    b.ToTable("Attendees");
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.BasketballCentre", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("AddressLine1")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("AddressLine2")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("ImageName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("Postcode")
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Suburb")
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("BasketballCentres");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AddressLine1 = "724 Victoria Rd",
                            AddressLine2 = "",
                            ImageName = "1.jpg",
                            Name = "ryde russ basketball club",
                            Postcode = "2112",
                            State = "NSW",
                            Suburb = "Ryde"
                        },
                        new
                        {
                            Id = 2,
                            AddressLine1 = "Church St",
                            AddressLine2 = "",
                            ImageName = "2.jpg",
                            Name = "Auburn Basketball Centre",
                            Postcode = "2141",
                            State = "NSW",
                            Suburb = "Lidcombe"
                        });
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.CourtRentFee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CentreId")
                        .HasColumnType("int");

                    b.Property<decimal>("ChargeFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CourtTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsCurrent")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.HasIndex("CentreId");

                    b.HasIndex("CourtTypeId");

                    b.ToTable("CourtRentFees");
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.CourtType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Type")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("CourtTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Type = "Full"
                        },
                        new
                        {
                            Id = 2,
                            Type = "Half"
                        });
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.Event", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("EventDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("EventName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<int>("TermId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TermId");

                    b.ToTable("Events");
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.NotificationBoard", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreateDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("NotificationText")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NotificationBoards");
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.Player", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("varchar(200)");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Mobile")
                        .HasColumnType("varchar(10)");

                    b.Property<string>("NickName")
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Password")
                        .HasColumnType("varchar(250)");

                    b.HasKey("Id");

                    b.ToTable("Players");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Email = "jinzhuo1783@gmail.com",
                            FirstName = "Zhuo",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "Jin",
                            Mobile = "0413100244",
                            NickName = "幫主",
                            Password = "1"
                        },
                        new
                        {
                            Id = 2,
                            Email = "xxxx@gmail.com",
                            FirstName = "Hai",
                            IsActive = true,
                            IsAdmin = true,
                            LastName = "SU",
                            Mobile = "0423233456",
                            NickName = "蘇海",
                            Password = "1"
                        });
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.Term", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourtRentFeeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreateDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TermName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("CourtRentFeeId");

                    b.ToTable("Terms");
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.Transaction", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<decimal>("Balance")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(255)");

                    b.Property<bool>("InOrOut")
                        .HasColumnType("bit");

                    b.Property<int>("PlayerId")
                        .HasColumnType("int");

                    b.Property<decimal>("TransactionFee")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId");

                    b.ToTable("Transactions");
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.Attendee", b =>
                {
                    b.HasOne("TDH.Basketball.Game.EF.Core.EntityClasses.Event", "Event")
                        .WithMany()
                        .HasForeignKey("EventId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TDH.Basketball.Game.EF.Core.EntityClasses.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TDH.Basketball.Game.EF.Core.EntityClasses.Player", "ReplacedPlayer")
                        .WithMany()
                        .HasForeignKey("ReplacedPlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.CourtRentFee", b =>
                {
                    b.HasOne("TDH.Basketball.Game.EF.Core.EntityClasses.BasketballCentre", "Centre")
                        .WithMany()
                        .HasForeignKey("CentreId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("TDH.Basketball.Game.EF.Core.EntityClasses.CourtType", "CourtType")
                        .WithMany()
                        .HasForeignKey("CourtTypeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.Event", b =>
                {
                    b.HasOne("TDH.Basketball.Game.EF.Core.EntityClasses.Term", "Term")
                        .WithMany()
                        .HasForeignKey("TermId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.Term", b =>
                {
                    b.HasOne("TDH.Basketball.Game.EF.Core.EntityClasses.CourtRentFee", "CourtRentFee")
                        .WithMany()
                        .HasForeignKey("CourtRentFeeId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });

            modelBuilder.Entity("TDH.Basketball.Game.EF.Core.EntityClasses.Transaction", b =>
                {
                    b.HasOne("TDH.Basketball.Game.EF.Core.EntityClasses.Player", "Player")
                        .WithMany()
                        .HasForeignKey("PlayerId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
